### ISSUE TITLE
Feature request for resource "aws-sso-scim_group_member"

### ISSUE THREAD

**Issue by quanght55** [BurdaForward/terraform-provider-aws-sso-scim#9]
Hi,
I just tested this provider and it worked very well but can you consider about assigning one user to multiple groups. I found out if I define one user into multiple groups. It remove user from this group and add to another group and finally, user only added to one group.
I wish I could do something like 

>  resource "aws-sso-scim_group_member" "main" {
>       + group_id = "xxxx"
>       + id       = (known after apply)
>       + user_id  = "yyyyyy,zzzzzz"
>     }
>

**Comment by JanKoppe** [comment]
Hello @quanght55,

I'm not sure I follow. It is totally possible to add the same user to multiple groups at the same time right now. The `aws-sso-scim_group_member` resource models the relationship of one user to one group. If you need to put a user into multiple groups, you need to create multiple instances of that resource, same with multiple users in one group.

Can you maybe post a full code excerpt of what you are trying to do right now?

**Comment by quanght55** [comment]
@JanKoppe Ah I can handle it using local-exec and AWS SSO SCIM API instead so I'm good now 😄 I will close this issue.
